### ISSUE TITLE
`npm i page2image -g` error

### ISSUE THREAD

**Issue by morolt** [Runjuu/page2image#4]
#### Node.js & npm version
Node.js: `node -v`;
v8.4.0
npm: `npm -v`
5.3.0
#### Operating system:
Ubuntu 16.04
#### Example CLI command or javascript code to reproduce the error
```
npm i page2image -g
/usr/local/node/bin/page2image -> /usr/local/node/lib/node_modules/page2image/buildBin/screenshot.js

> puppeteer@0.10.2 install /usr/local/node/lib/node_modules/page2image/node_modules/puppeteer
> node install.js

fs.js:891
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/local/node/lib/node_modules/page2image/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:891:18)
    at Object.downloadRevision (/usr/local/node/lib/node_modules/page2image/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/page2image/node_modules/puppeteer/install.js:33:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-04T07_45_50_282Z-debug.log
```

#### Error infos:
```bash
mkdir -p /usr/local/node/lib/node_modules/page2image/node_modules/puppeteer/.local-chromium
npm i page2image -g
#同样的错误
```

**Comment by Runjuu** [comment]
it seems like npm have not enough permission to write. you could try using `sudo` command to install `page2image`

```bash
sudo npm i page2image -g
```

**Comment by Runjuu** [comment]
also, if you do not want using `sudo`, you would follow this [tutorial](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to fix npm permissions

**Comment by morolt** [comment]
使用的是root用户

**Comment by Runjuu** [comment]
well, It seems like a bug of puppeteer 🤔 https://github.com/GoogleChrome/puppeteer/issues/375
